# Numpy

Numerical Pandas

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 56, 78])

In [4]:
a

array([ 1,  2,  3,  4, 56, 78])

In [5]:
type(a) #nd --> n dimensional array

numpy.ndarray

In [6]:
# positive indexing
# direction Left -->> Right
# starts from 0

a = np.array([12,3,3,56,78])
a[0]

12

In [7]:
# negative indexing
# direction RIGHT -->> LEFT
# Starts from -1

a = np.array([12,3,3,56,78])
a[-2]

56

In [8]:
a.size

5

In [9]:
a.ndim

1

In [10]:
a.shape

(5,)

In [11]:
a.itemsize

4

In [12]:
b = np.array([1,2,3,"4", 5.6])

In [13]:
b.itemsize

128

In [14]:
c = np.array([[[[[5]]]]])

In [15]:
c.ndim

5

In [16]:
# different ways of creating an array
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [18]:
a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
a.shape

(4, 4)

In [20]:
a = np.full((3,5),23)
a

array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [21]:
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
#slicing
a[1:6]

array([1, 2, 3, 4, 5])

In [24]:
a[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23])

In [25]:
a[:-5]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [26]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
a[1, 1:] #[row,column]

array([5, 6, 7])

In [28]:
a[2:,1]

array([ 9, 13, 17, 21])

In [29]:
a[4,2]

18

In [30]:
a[0:-3,3]

array([ 3,  7, 11])

In [31]:
b = np.arange(30).reshape(6,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [32]:
b[1, 1:4]

array([6, 7, 8])

In [33]:
b[:, -3]
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [37]:
b[0:4,2]

array([ 2,  7, 12, 17])

In [38]:
b[3, 1:]

array([16, 17, 18, 19])

In [39]:
b[3:,2]

array([17, 22, 27])

In [40]:
a = np.array([23,24,2,25])
b = np.array([11,22,4,33])

In [41]:
a + b

array([34, 46,  6, 58])

In [42]:
a + b

array([34, 46,  6, 58])

In [43]:
a.max()

25

In [44]:
a.min()

2

In [45]:
a.mean()

18.5

In [46]:
a * b

array([253, 528,   8, 825])

In [47]:
c = np.arange(30).reshape(6,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [48]:
c.transpose()

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [49]:
d = np.array([1,2,3,45 + 66j])
d

array([ 1. +0.j,  2. +0.j,  3. +0.j, 45.+66.j])

In [50]:
d.conj()

array([ 1. -0.j,  2. -0.j,  3. -0.j, 45.-66.j])